config/routes.rb
Rails.application.routes.draw do
  get 'auth/login', to: 'sessions#new', as: 'login'
  get 'auth/logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:new, :create, :destroy]

  resources :items
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :room
  validates :name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :restrict_access

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def restrict_access
    unless current_user
      redirect_to '/auth/login'
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :restrict_access

  def index
    @page_title = 'House Items (List)'
    @button_action = 'Add Item'
    @show_action_button = true
    @action_link = '/items/new'
    @items = Item.all
  end

  def new
    @page_title = 'New Item'
    @rooms = Room.all
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to '/'
    else
      render 'items/new'
    end
  end

  def edit
    @item = Item.find(params[:id])
    @page_title = 'Update Item: ' + @item.name
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to '/'
    else
      render 'items/edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :room_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false

  def new
    render 'auth/login'
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render 'auth/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :restrict_access
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @page_title = 'Users'
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @page_title = 'New User'
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @page_title = 'Editing User'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |f|  %>
    <% if @item.errors.any? %>
        <div class="alert alert-warning" role="alert">
          <strong><%= pluralize(@item.errors.count, "error") %>
          prohibited this item from being saved:</strong>
          <ul>
              <% @item.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name,  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :room %><br>
      <%= f.select :room_id, Room.all.collect { |r| [ r.name, r.id ] }, { :prompt => "Choose" }, { :class => 'custom-select' } %>
    </div>

    <div>
    <%= f.submit 'Create Item', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Item</th>
        <th>Room</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
    <% @items.each_with_index do |item, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= item.name %></td>
        <td><%= item.room.name %></td>
        <td><a href="<%= edit_item_path(item) %>"><button type="button" class="btn btn-secondary btn-sm">Edit</button></a></td>
        <td><%= link_to 'Delete', item_path(item),
                                  method: :delete,
                                  data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
   

app/views/items/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= @page_title %> - housethings</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <%= stylesheet_link_tag "main" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/5bd68ed98e.js" crossorigin="anonymous"></script>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light static-top">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag "housethings-alt.png" %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <span class="navbar-text dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="far fa-user-circle"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/auth/logout">Log out</a>
        </div>
      </span>
    </div>
  </nav>
  <div class="container">
    <!-- page header goes here-->
    <div class="page-header">
      <div class="row">
        <div class="col">
          <h3><%= @page_title %></h3>
        </div>
        <div class="col">
          <% if @show_action_button %>
          <a href="<%= @action_link %>" class="btn btn-primary btn-icon-split float-right">
            <span class="icon text-white-50">
                <i class="fas fa-plus"></i>
            </span>
            <span class="text"><%= @button_action %></span>
        </a>
        <% end %>
        </div>
      </div>
    </div>
    <div class="page-content">
      <!-- the page content goes here -->
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <strong><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</strong>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create User', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>